### ISSUE TITLE
Proyecto final de Yanet

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/proyecto-pulsador-eq-erick-yanet-lourdes-1as#1]
[PROYECTO FINALLL-YANET.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-pulsador-eq-erick-yanet-lourdes-1as/files/7819248/PROYECTO.FINALLL-YANET.pdf)

**Comment by josealfredo79** [comment]
Falta realizar el circuito en físico

**Comment by josealfredo79** [comment]
Revisado
